import type { ProvinceOption } from '../types/province'

export const PROVINCES: ProvinceOption[] = [
  { label: '北京市', value: 'beijing', pinyin: 'beijing', sortOrder: 1 },
  { label: '天津市', value: 'tianjin', pinyin: 'tianjin', sortOrder: 2 },
  { label: '上海市', value: 'shanghai', pinyin: 'shanghai', sortOrder: 3 },
  { label: '重庆市', value: 'chongqing', pinyin: 'chongqing', sortOrder: 4 },
  { label: '河北省', value: 'hebei', pinyin: 'hebei', sortOrder: 5 },
  { label: '山西省', value: 'shanxi', pinyin: 'shanxi', sortOrder: 6 },
  { label: '辽宁省', value: 'liaoning', pinyin: 'liaoning', sortOrder: 7 },
  { label: '吉林省', value: 'jilin', pinyin: 'jilin', sortOrder: 8 },
  { label: '黑龙江省', value: 'heilongjiang', pinyin: 'heilongjiang', sortOrder: 9 },
  { label: '江苏省', value: 'jiangsu', pinyin: 'jiangsu', sortOrder: 10 },
  { label: '浙江省', value: 'zhejiang', pinyin: 'zhejiang', sortOrder: 11 },
  { label: '安徽省', value: 'anhui', pinyin: 'anhui', sortOrder: 12 },
  { label: '福建省', value: 'fujian', pinyin: 'fujian', sortOrder: 13 },
  { label: '江西省', value: 'jiangxi', pinyin: 'jiangxi', sortOrder: 14 },
  { label: '山东省', value: 'shandong', pinyin: 'shandong', sortOrder: 15 },
  { label: '河南省', value: 'henan', pinyin: 'henan', sortOrder: 16 },
  { label: '湖北省', value: 'hubei', pinyin: 'hubei', sortOrder: 17 },
  { label: '湖南省', value: 'hunan', pinyin: 'hunan', sortOrder: 18 },
  { label: '广东省', value: 'guangdong', pinyin: 'guangdong', sortOrder: 19 },
  { label: '海南省', value: 'hainan', pinyin: 'hainan', sortOrder: 20 },
  { label: '四川省', value: 'sichuan', pinyin: 'sichuan', sortOrder: 21 },
  { label: '贵州省', value: 'guizhou', pinyin: 'guizhou', sortOrder: 22 },
  { label: '云南省', value: 'yunnan', pinyin: 'yunnan', sortOrder: 23 },
  { label: '陕西省', value: 'shaanxi', pinyin: 'shaanxi', sortOrder: 24 },
  { label: '甘肃省', value: 'gansu', pinyin: 'gansu', sortOrder: 25 },
  { label: '青海省', value: 'qinghai', pinyin: 'qinghai', sortOrder: 26 },
  { label: '内蒙古自治区', value: 'neimenggu', pinyin: 'neimenggu', sortOrder: 27 },
  { label: '广西壮族自治区', value: 'guangxi', pinyin: 'guangxi', sortOrder: 28 },
  { label: '西藏自治区', value: 'xizang', pinyin: 'xizang', sortOrder: 29 },
  { label: '宁夏回族自治区', value: 'ningxia', pinyin: 'ningxia', sortOrder: 30 },
  { label: '新疆维吾尔自治区', value: 'xinjiang', pinyin: 'xinjiang', sortOrder: 31 }
]
